Repository gramps-project/addons-source, pull requests merged in 2018-02, with the labels that each got.

#106 Fix NetworkChart gpr to display missing dependencies correctly
  NetworkChart/NetworkChart.gpr.py
Labels: bug

#107 Fix PlaceCompletion for some issues
  PlaceCompletion/PlaceCompletion.py
  PlaceCompletion/placecompletion.glade
Labels: bug

#110 GoogleMapXML fix 2 errors[gramps50]
  GoogleEarthWriteKML/GoogleEarthWriteKML.gpr.py
  GoogleEarthWriteKML/GoogleEarthWriteKML.py
Labels: bug

#111 GoogleEarthWriteKML output log Missing coordinates[gramps50]
  GoogleEarthWriteKML/GoogleEarthWriteKML.gpr.py
  GoogleEarthWriteKML/GoogleEarthWriteKML.py
Labels: enhancement

#112 PostgreSQL, check for prerequisites
  PostgreSQL/postgresql.gpr.py
Labels: enhancement

#113 Fix Descendant Book crash
  DescendantBooks/CollectAscendants.py
Labels: bug

#114 Fix Calculate estimated dates addon[gramps50]
  CalculateEstimatedDates/CalculateEstimatedDates.py
Labels: bug

#115 Add View specific icons to four addons[gramps50]
  GraphView/MANIFEST
  GraphView/gramps-graph.svg
  GraphView/graphview.gpr.py
  HtreePedigreeView/HtreePedigreeView.gpr.py
  HtreePedigreeView/MANIFEST
  HtreePedigreeView/gramps-htree.svg
  QuiltView/MANIFEST
  QuiltView/QuiltView.gpr.py
  QuiltView/gramps-quilt.svg
  TimelinePedigreeView/MANIFEST
  TimelinePedigreeView/TimelinePedigreeView.gpr.py
  TimelinePedigreeView/gramps-timelinepedigree.svg
Labels: enhancement

#116 Add View specific icons to three addons( #115)[gramps42]
  GraphView/MANIFEST
  GraphView/gramps-graph.svg
  GraphView/graphview.gpr.py
  HtreePedigreeView/HtreePedigreeView.gpr.py
  HtreePedigreeView/MANIFEST
  HtreePedigreeView/gramps-htree.svg
  TimelinePedigreeView/MANIFEST
  TimelinePedigreeView/TimelinePedigreeView.gpr.py
  TimelinePedigreeView/gramps-timelinepedigree.svg
Labels: enhancement

#117 [GraphView]refactor code (add_spouses / Animation class) & cleanup[gramps50]
  GraphView/graphview.py
Labels: enhancement

#118 [Network chart]Use standard Name/Language and Date Format options. Pylint code[gramps50]
  NetworkChart/NetworkChart.gpr.py
  NetworkChart/NetworkChart.py
Labels: Documentation, enhancement

#119 Fix Clipboard Gramplet exception with data present when changing db.
  ClipboardGramplet/ClipboardGramplet.py
Labels: bug
