Repository gramps-project/addons-source, pull requests merged in 2018-03, with the labels that each got.

#123 [FamilySheet]Fix Report exception on missing spouse[gramps50]
  FamilySheet/FamilySheet.py
Labels: bug

#121 [FamilySheet]Enable CLI & book report usage /Misc help[gramps50]
  FamilySheet/FamilySheet.gpr.py
  FamilySheet/FamilySheet.py
Labels: enhancement

#124 Update ImportGramplet to work with gramps50
  ImportGramplet/ImportGramplet.py
Labels: bug

#125 Fix Gedcom Extensions Addon for exception on gramps50
  GedcomExtensions/GedcomExtensions.py
Labels: bug

#126 Fix DynamicWeb for exception on config setting
  DynamicWeb/dynamicweb.py
Labels: bug

#122 [CollectionsClipboardGramplet]Fix for db change and other issues[gramps50]
  ClipboardGramplet/ClipboardGramplet.gpr.py
  ClipboardGramplet/ClipboardGramplet.py
Labels: bug

#120 [GraphView]Add popup menu[gramps50]
  GraphView/graphview.py
  GraphView/po/ru-local.po
Labels: Documentation, enhancement

#127 [GraphView] fix generation spinners and popup [gramps50]
  GraphView/graphview.py
Labels: bug, enhancement

#128 [Quilt View]Add popup menu and other request.
  QuiltView/QuiltView.gpr.py
  QuiltView/QuiltView.py
Labels: enhancement

#129 [Quilt View] Apply changes from 5.0 to master
  QuiltView/QuiltView.py
Labels: enhancement

#131 [GedcomExtensions]fix for filtered data[gramps50]
  GedcomExtensions/GedcomExtensions.py
Labels: bug
