Repository gramps-project/addons-source, pull requests merged in 2018-05, with the labels that each got.

#136 Fix DownloadMedia to complete when errors are present (Gramps50)
  DownloadMedia/DownloadMedia.py
Labels: bug

#137 Fixes for ListeEclair addon to work with Gramps50 branch
  ListeEclair/ListeEclair.py
Labels: bug

#138 [FamilySheet]Add Table of Contents inside Book Report[gramps50]
  FamilySheet/FamilySheet.py
Labels: Documentation, enhancement

#141 [ GraphView]Add Slovak translation[gramps51]
  GraphView/po/sk-local.po
Labels: enhancement

#130 [ancestorfill]Fix & update for bookreport[gramps50]
  AncestorFill/AncestorFill.gpr.py
  AncestorFill/AncestorFill.py
Labels: bug, enhancement

#132 [SourcesCitationsReport]Fixs for[gramps50]
  SourcesCitationsReport/SourcesCitationsReport.gpr.py
  SourcesCitationsReport/SourcesCitationsReport.py
Labels: bug

#142 [DeepConnectionsGramplet]Update Slovak translation[gramps51]
  DeepConnectionsGramplet/po/sk-local.po
Labels: Translation

#144 [PrerequisitesChecker]Fixes UnboundLocalError[gramps50]
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py
Labels: bug

#143 [FamilySheet]Add Slovak translation[gramps51]
  FamilySheet/po/sk-local.po
Labels: Translation

#146 [PrerequisitesChecker]Fixes UnboundLocalError(#144)[gramps50]
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.gpr.py
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py
Labels: bug

#147 [PrerequisitesChecker]Fixes Checks for versions[gramps50]
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.gpr.py
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py
Labels: bug

#148 [PrerequisitesChecker]Fixes ValueError goocanvas[gramps50]
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.gpr.py
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py
Labels: bug

#149 [GetGOV]Fix config setting name[gramps50]
  GetGOV/getgov.gpr.py
  GetGOV/getgov.py
Labels: bug
