Repository gramps-project/addons-source, pull requests merged in 2019-09, with the labels that each got.

#219 Fix Sqlite test
  Sqlite/tests/test_sqlite.py
Labels: bug

#220 [HeadlineNews]Fix text display & repeating word[gramps51]
  HeadlineNewsGramplet/HeadlineNewsGramplet.gpr.py
  HeadlineNewsGramplet/HeadlineNewsGramplet.py
Labels: bug

#221 [HeadlineNews]Updates & cleanup[gramps51]
  HeadlineNewsGramplet/HeadlineNewsGramplet.py
Labels: bug

#222 [HeadlineNews]Updates & cleanup[gramps50]
  HeadlineNewsGramplet/HeadlineNewsGramplet.py
Labels: bug

#224 [HeadlineNews]Updates & cleanup[gramps42]
  HeadlineNewsGramplet/HeadlineNewsGramplet.gpr.py
  HeadlineNewsGramplet/HeadlineNewsGramplet.py
Labels: bug

#225 [PreReq]Formating add line[gramps51]
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.gpr.py
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py
Labels: bug

#202 [GraphView] Add search capability[gramps51]
  GraphView/graphview.py
  GraphView/search_widget.py
Labels: Documentation, enhancement

#217 [DeepConnectionsGramplet]Updated Catalan translation[gramps51]
  DeepConnectionsGramplet/po/ca-local.po
Labels: Translation

#227 [GraphView]only check image_path when self.show_images=true[gramps51]
  GraphView/graphview.py
Labels: bug

#218 [MediaReport] A media text report [gramps51]
  MediaReport/media_report.gpr.py
  MediaReport/media_report.py
Labels: Documentation, enhancement

#228 [DeepConnectionsGramplet]Updated Catalan translation[gramps51]
  DeepConnectionsGramplet/po/ca-local.po
Labels: Translation

#204 [AssociationsTool]Enhanced by calling relcal[gramps52]
  AssociationsTool/associationstool.py
Labels: enhancement

#145 [FamilySheet]Sort person events by start date[gramps51]
  FamilySheet/FamilySheet.py
Labels: enhancement

#208 [GraphView]Add options for Vertical/horizontal spacing between nodes[gramps51]
  GraphView/graphview.py
Labels: Documentation, enhancement

#213 [BirthdaysGramplet] Add 'Only show birthdays with tag' functionality[gramps51]
  BirthdaysGramplet/BirthdaysGramplet.py
Labels: Documentation, enhancement

#209 [GraphView] keep multiple spouses positioned together [gramps51]
  GraphView/graphview.py
Labels: enhancement

#229 [Graph View]Display invalid dates when show_full_dates==True[gramps51]
  GraphView/graphview.py
Labels: Documentation, enhancement

#231 [Query]Hebrew translation[gramps51]
  Query/po/he-local.po
Labels: Translation

#194 [PhotoTaggingGramplet] add age column[gramps51]
  PhotoTaggingGramplet/PhotoTaggingGramplet.py
  PhotoTaggingGramplet/po/ru-local.po
  PhotoTaggingGramplet/po/template.pot
Labels: Documentation, enhancement

#234 [PluginManager] Hebrew translation [v51]
  PluginManager/po/he-local.po
Labels: Translation

#233 [Graphview]Fix tag colors on boxes[gramps51]
  GraphView/graphview.py
Labels: bug
