Repository gramps-project/addons-source, pull requests merged in 2019-01, with the labels that each got.

#183 [DynamicWeb]Update OpenStreemaps[gramps50]
  DynamicWeb/templates/dwr_default/data/dwr_start.js
Labels: bug

#182 [PreReqChecker]List installed Locales[gramps50]
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py
Labels: enhancement

#181 [PluginManager] change filter Entry class to SearchEntry[gramps50]
  PluginManager/PluginManager.py
  PluginManager/po/ru-local.po
Labels: Documentation, enhancement

#184 Minor enhancements and fixes for GenealogyTree[gramps50]
  GenealogyTree/gt_sandclock.py
Labels: Documentation, bug, enhancement
