Repository gramps-project/addons-source, pull requests merged in 2019-07, with the labels that each got.

#201 [GraphView] right click menu updates [Gramps50] recreation
  GraphView/graphview.py
Labels: enhancement

#206 [BirthdayGramplet]Add 'ignore birthday' functionality[gramps50]
  BirthdaysGramplet/BirthdaysGramplet.gpr.py
  BirthdaysGramplet/BirthdaysGramplet.py
Labels: Documentation, enhancement

#211 New [RemoveTagTool] addon [gramps50]
  RemoveTagTool/RemoveTagTool.gpr.py
  RemoveTagTool/RemoveTagTool.py
Labels: Documentation, enhancement

#212 OSM forward all http request to https[gramps52]
  DynamicWeb/templates/dwr_default/data/dwr_start.js
Labels: enhancement

#210 [DynamicWeb] Add Slovak translation [gramps51]
  DynamicWeb/po/sk-local.po
Labels: Translation
