Repository gramps-project/addons-source, pull requests merged in 2019-10, with the labels that each got.

#235 [GraphView]Add Persons node themes & Avatars[v51]
  GraphView/graphview.py
  GraphView/person_female.png
  GraphView/person_male.png
Labels: Documentation, enhancement

#238 [GraphView]Fix MANIFEST for Persons Avatars[v51](#235)
  GraphView/MANIFEST
Labels: bug

#237 [Graphview] Label position and font [v51]
  GraphView/graphview.py
Labels: bug

#239 [PlaceCleanup] Hebrew translation [Gramps51]
  PlaceCleanup/po/he-local.po
Labels: Translation

#242 [TMGimporter]Remove WIP addon from 50 branch[50]
  TMGimporter/importtmg.gpr.py
  TMGimporter/importtmg.py
  TMGimporter/importtmgunsupported.py
  TMGimporter/lib/__init__.py
  TMGimporter/lib/libtmg.glade
  TMGimporter/lib/libtmg.py
  TMGimporter/lib/libtmgdate.py
  TMGimporter/lib/libtmgextractsqz.py
  TMGimporter/lib/libtmgtables.py
  TMGimporter/po/de-local.po
  TMGimporter/po/hr-local.po
  TMGimporter/po/ru-local.po
  TMGimporter/po/template.pot
Labels: bug

#241 [TMGimporter]Minor update from August 2018[v51]
  TMGimporter/README.md
  TMGimporter/importtmg.gpr.py
  TMGimporter/importtmg.py
  TMGimporter/importtmgunsupported.py
  TMGimporter/lib/__init__.py
  TMGimporter/lib/libtmg.glade
  TMGimporter/lib/libtmgdate.py
  TMGimporter/lib/libtmgextractsqz.py
  TMGimporter/lib/libtmgtables.py
  TMGimporter/libtmg.glade
  TMGimporter/libtmg.py
  TMGimporter/po/de-local.po
  TMGimporter/po/hr-local.po
  TMGimporter/po/ru-local.po
  TMGimporter/po/template.pot
Labels: enhancement

#240 [GraphView] choose font option [v51]
  GraphView/graphview.py
Labels: Work in progress, enhancement

#244 [TMGimporter]Remove Older WIP addon from master branch[52]
  TMGimporter/importtmg.gpr.py
  TMGimporter/importtmg.py
  TMGimporter/importtmgunsupported.py
  TMGimporter/lib/__init__.py
  TMGimporter/lib/libtmg.glade
  TMGimporter/lib/libtmg.py
  TMGimporter/lib/libtmgdate.py
  TMGimporter/lib/libtmgextractsqz.py
  TMGimporter/lib/libtmgtables.py
  TMGimporter/po/de-local.po
  TMGimporter/po/ru-local.po
  TMGimporter/po/template.pot
Labels: bug

#246 Assorted Gramplets Cleanups for Context Menus etc[51]
  BirthdaysGramplet/BirthdaysGramplet.gpr.py
  BirthdaysGramplet/po/template.pot
  ClockGramplet/ClockGramplet.gpr.py
  ClockGramplet/po/template.pot
  DescendantCount/DescendantCount.gpr.py
  DescendantCount/po/template.pot
  ImportGramplet/ImportGramplet.gpr.py
  ImportGramplet/po/template.pot
  LastChange/LastChange.gpr.py
  LastChange/po/template.pot
  PythonGramplet/PythonGramplet.gpr.py
  PythonGramplet/po/template.pot
  RelatedRelativesGramplet/RelatedRelativesGramplet.gpr.py
  RelatedRelativesGramplet/po/template.pot
  WordleGramplet/WordleGramplet.gpr.py
  WordleGramplet/po/template.pot
  lxml/etreeGramplet.gpr.py
  lxml/lxmlGramplet.gpr.py
  lxml/po/template.pot
Labels: bug

#255 [DateCalculatorGramplet]Fix height on Dashboard[51]
  DateCalculator/DateCalculator.gpr.py
Labels: bug
