Repository gramps-project/addons-source, pull requests merged in 2020-02, with the labels that each got.

#271 Fix NetworkChart to work with v2.x of networkx library
  NetworkChart/NetworkChart.py
Labels: bug

#264 Dynamic Web: Sort the citation lists and indexes[v51]
  DynamicWeb/templates/dwr_default/data/dwr.js
Labels: enhancement

#279 Fix Forms Gramplet to allow forms to be retrieved when language changes
  Form/form.py
Labels: bug

#286 New geography ancestor view
  GeoAncestor/GeoAncestor.gpr.py
  GeoAncestor/GeoAncestor.py
  GeoAncestor/MANIFEST
  GeoAncestor/geo-ancestor.svg
Labels: enhancement

#261 [Topola] Added support for exposing files referenced from the GEDCOM file [gramps51]
  Topola/Topola.gpr.py
  Topola/topola.py
  Topola/topola_server.py
Labels: Documentation, enhancement

#256 [NLWebConnectPack]New plugin[v52]
  NLWebConnectPack/NLWebPack.gpr.py
  NLWebConnectPack/NLWebPack.py
  NLWebConnectPack/po/de-local.po
  NLWebConnectPack/po/fr-local.po
  NLWebConnectPack/po/nl-local.po
  NLWebConnectPack/po/template.pot
Labels: Documentation, enhancement

#262 [LaTeX genealogytree]Add the Language selector[v51]
  GenealogyTree/gt_ancestor.py
  GenealogyTree/gt_descendant.py
  GenealogyTree/gt_grandparent.py
  GenealogyTree/gt_sandclock.py
Labels: Documentation, enhancement
