Repository gramps-project/addons-source, pull requests merged in 2025-05, with the labels that each got.

#730 Prerequisites checker updates
  PrerequisitesCheckerGramplet/PrerequisitesCheckerGramplet.py
Labels: enhancement

#732 Fixes #13710 update JSON import/export for Gramps60
  JSON/JSONExport.py
  JSON/JSONImport.py
Labels: bug

#731 Bug13706
  Differences/differences.py
Labels: bug

#726 Translations update from Hosted Weblate
  po/ar.po
  po/bg.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fi.po
  po/fr.po
  po/he.po
  po/hr.po
  po/hu.po
  po/is.po
  po/it.po
  po/ja.po
  po/lt.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sv.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Translation
