Repository gramps-project/addons-source, pull requests merged in 2025-01, with the labels that each got.

#631 Added new Italian translation for AvatarGenerator addon
  AvatarGenerator/po/it-local.po
Labels: Translation

#629 Tentative fix for crash in Form editor
  Form/editform.py
Labels: bug

#632 DateCalculator: Make the enter key trigger calculation
  DateCalculator/DateCalculator.py
Labels: enhancement
